# Generated by Django 4.0.4 on 2022-05-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Database',
            new_name='DB',
        ),
        migrations.AlterModelTable(
            name='db',
            table='db',
        ),
    ]
